<?php /** @var BearCosmetic\Exrate\Block\Feed $block */ ?>
<table>
    <tr>
        <th colspan="2">Ngoại tệ</th>
        <th colspan="2">Mua</th>
        <th rowspan="2">Bán</th>
    </tr>
    <tr>
        <th>Tên ngoại tệ</th>
        <th>Mã NT</th>
        <th>Tiền mặt</th>
        <th>Chuyển khoản</th>
    </tr>
    <?php foreach($block->fetchExrate() as $exrate): ?>
        <tr>
            <td><?php echo $exrate['@attributes']['CurrencyName'] ?></td>
            <td><?php echo $exrate['@attributes']['CurrencyCode'] ?></td>
            <td><?php echo $exrate['@attributes']['Buy'] ?></td>
            <td><?php echo $exrate['@attributes']['Transfer'] ?></td>
            <td><?php echo $exrate['@attributes']['Sell'] ?></td>
        </tr>
    <?php endforeach; ?>
</table>
