<div class="container">
    <div class="app-title">
        <p>Weather</p>
    </div>
    <div class="notification"> </div>
    <div class="weather-container">
        <div class="weather-icon">
            <img src="icons/unknown.png" alt="">
        </div>
        <div class="temperature-value">
            <p>- °<span>C</span></p>
        </div>
        <div class="temperature-description">
            <p> - </p>
        </div>
        <div class="location">
            <p>-</p>
        </div>
    </div>
</div>